export const styles = {
  browserCenterWrapper: { display: 'flex', justifyContent: 'center', alignItems: 'center', width: '100vw', height: '100vh', backgroundColor: '#3b3b3b', margin: 0 },
  phoneContainer: { width: '375px', height: '90vh', maxHeight: '812px', backgroundColor: '#f5f7fb', display: 'flex', flexDirection: 'column', overflow: 'hidden', boxShadow: '0 4px 30px rgba(0,0,0,0.3)' },
  header: { backgroundColor: '#3832a8', padding: '45px 20px 20px 20px', color: 'white', flexShrink: 0 },
  headerTop: { display: 'flex', justifyContent: 'space-between', alignItems: 'center' },
  title: { fontSize: '18px', fontWeight: 'bold', margin: 0 },
  searchSection: { padding: '20px 20px 10px 20px' },
  searchContainer: { position: 'relative', boxShadow: '0 4px 10px rgba(0, 0, 0, 0.05)', borderRadius: '25px', backgroundColor: 'white' },
  searchIconPos: { position: 'absolute', left: '15px', top: '10px' },
  searchInput: { width: '100%', padding: '12px 12px 12px 50px', borderRadius: '25px', border: 'none', fontSize: '14px', outline: 'none', boxSizing: 'border-box' },
  scrollContent: { flex: 1, overflowY: 'auto' },
  section: { padding: '15px 20px' },
  sectionTitle: { fontSize: '17px', fontWeight: 'bold', marginBottom: '15px', color: '#111' },
  categoryGrid: { display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: '12px' },
  categoryBox: { height: '65px', borderRadius: '12px', display: 'flex', alignItems: 'center', justifyContent: 'center', color: 'white', fontSize: '11px', fontWeight: 'bold', textAlign: 'center' },
  card: { backgroundColor: 'white', borderRadius: '15px', padding: '15px', marginBottom: '15px', cursor: 'pointer' },
  cardContent: { display: 'flex', gap: '15px' },
  cardImage: { width: '85px', height: '65px', borderRadius: '10px', objectFit: 'cover' },
  cardText: { display: 'flex', flexDirection: 'column', justifyContent: 'center' },
  centerName: { margin: '0 0 5px 0', fontSize: '15px', fontWeight: 'bold', color: '#090909' },
  location: { fontSize: '13px', color: '#666', marginBottom: '4px' },
  rating: { fontSize: '13px', color: '#666' },
  formInput: { width: '100%', border: 'none', borderRadius: '10px', backgroundColor: '#f9f4f4', color: '#070505', padding: '12px 15px', outline: 'none', fontSize: '14px', boxSizing: 'border-box' },
  confirmBtn: { width: '100%', backgroundColor: '#3832a8', color: '#f7f1f1', border: 'none', padding: '14px', borderRadius: '15px', fontWeight: 'bold', fontSize: '16px' }
};